#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

cp /etc/timestamp "$DESTDIR"/etc

cp -r /usr/share/initramfs-tools/cow "$DESTDIR"

copy_exec /bin/bash /bin

copy_exec /bin/chmod /bin
copy_exec /bin/cp /bin
copy_exec /bin/mount /bin
copy_exec /usr/bin/cmp /bin

copy_exec /bin/sed /bin
copy_exec /usr/bin/awk /bin

copy_exec /sbin/kpartx /sbin
copy_exec /sbin/mke2fs /sbin

copy_exec /usr/bin/sha1sum /bin
copy_exec /usr/bin/xxd /bin

manual_add_modules brd
manual_add_modules dm_mod
manual_add_modules dm_snapshot

exit 0
