#!/bin/sh

set -e

PREREQ="mdadm busybox"

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

cp /etc/timestamp "$DESTDIR"/etc

cp -r /usr/share/initramfs-tools/cow "$DESTDIR"

replace() {
    local prefix="$1"; shift
    for file in "$@"; do
        rm -f "$DESTDIR/bin/$file"
        copy_exec "/$prefix/$file" /bin
    done
}

replace bin     bash chmod cp ls mount sed
replace usr/bin cmp awk wc xxd sha1sum
replace sbin    kpartx mke2fs

manual_add_modules brd
manual_add_modules dm_mod
manual_add_modules dm_snapshot

# erase MDADM generated config and use auto detection
echo -n > "$DESTDIR/etc/mdadm/mdadm.conf"
echo -n > "$DESTDIR/conf/mdadm"

exit 0
