#!/bin/sh

set -e

PREREQ="mdadm busybox"

prereqs() {
	echo "${PREREQ}"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

cp -r /usr/share/initramfs-tools/cow "$DESTDIR"
cp /etc/timestamp /etc/cow.conf "$DESTDIR"/etc

replace() {
    local prefix=$1; shift
    for file in "$@"; do
        rm -f "$DESTDIR/bin/$file"
        copy_exec "/$prefix/$file" /bin
    done
}

replace bin      bash chmod cp date dd ls mount mountpoint rm sed touch
replace usr/bin  cmp awk wc xxd sha1sum
replace sbin     blkid blockdev kpartx losetup \
                 e2fsck fsck logsave mke2fs

for link in fsck.ext2 fsck.ext3 fsck.ext4; do
    ln -s /bin/e2fsck "$DESTDIR/bin/$link"
done

manual_add_modules brd
manual_add_modules dm_mod
manual_add_modules dm_snapshot

manual_add_modules softdog
manual_add_modules loop

# erase MDADM generated config and use auto detection
echo -n > "$DESTDIR/etc/mdadm/mdadm.conf"
echo -n > "$DESTDIR/conf/mdadm"
