#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

arch=`dpkg-architecture -qDEB_HOST_MULTIARCH`

copy_exec /lib/"$arch"/libnss_files.so.*
copy_exec /lib/"$arch"/libnss_dns.so.*
copy_exec /lib/"$arch"/libnss_compat.so.*

mkdir -p "$DESTDIR"/etc
cp -p /etc/nsswitch.conf "$DESTDIR"/etc
