#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

if [[ "$cowsrc" != network ]]; then
    . /scripts/functions
    configure_networking
fi
